-- Initial reference data seed for Oracle.
-- This script inserts or updates service operation codes used by /api/v1/codes/*.
-- Safe to re-run: each section uses MERGE by code.
--
-- Tables:
--   REGION_CODE
--   AVAILABLE_TIME_SLOT_CODE
--   PROJECT_TYPE_CODE

SET DEFINE OFF;

MERGE INTO PROJECT_TYPE_CODE t
USING (
    SELECT 'HOSPITAL_COMPANION' PROJECT_TYPE_CODE, '병원 동행' PROJECT_TYPE_NAME, 1 SORT_ORDER FROM DUAL UNION ALL
    SELECT 'GOVERNMENT_OFFICE_COMPANION', '관공서 업무 동행', 2 FROM DUAL UNION ALL
    SELECT 'RETURN_HOME_COMPANION', '귀가 동행', 3 FROM DUAL UNION ALL
    SELECT 'OUTING_COMPANION', '외출 동행', 4 FROM DUAL UNION ALL
    SELECT 'GROCERY_SHOPPING', '장보기 동행', 5 FROM DUAL UNION ALL
    SELECT 'DAILY_LIFE_SUPPORT', '생활 지원', 6 FROM DUAL UNION ALL
    SELECT 'OTHER', '기타', 7 FROM DUAL
) s
ON (t.PROJECT_TYPE_CODE = s.PROJECT_TYPE_CODE)
WHEN MATCHED THEN UPDATE SET
    t.PROJECT_TYPE_NAME = s.PROJECT_TYPE_NAME,
    t.SORT_ORDER = s.SORT_ORDER,
    t.ACTIVE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (
    PROJECT_TYPE_CODE,
    PROJECT_TYPE_NAME,
    SORT_ORDER,
    ACTIVE_YN
) VALUES (
    s.PROJECT_TYPE_CODE,
    s.PROJECT_TYPE_NAME,
    s.SORT_ORDER,
    'Y'
);

MERGE INTO AVAILABLE_TIME_SLOT_CODE t
USING (
    SELECT 'MORNING' TIME_SLOT_CODE, '오전' TIME_SLOT_NAME, 540 START_MINUTE, 720 END_MINUTE, 1 SORT_ORDER FROM DUAL UNION ALL
    SELECT 'AFTERNOON', '오후', 720, 1020, 2 FROM DUAL UNION ALL
    SELECT 'EVENING', '저녁', 1020, 1260, 3 FROM DUAL
) s
ON (t.TIME_SLOT_CODE = s.TIME_SLOT_CODE)
WHEN MATCHED THEN UPDATE SET
    t.TIME_SLOT_NAME = s.TIME_SLOT_NAME,
    t.START_MINUTE = s.START_MINUTE,
    t.END_MINUTE = s.END_MINUTE,
    t.SORT_ORDER = s.SORT_ORDER,
    t.ACTIVE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (
    TIME_SLOT_CODE,
    TIME_SLOT_NAME,
    START_MINUTE,
    END_MINUTE,
    SORT_ORDER,
    ACTIVE_YN
) VALUES (
    s.TIME_SLOT_CODE,
    s.TIME_SLOT_NAME,
    s.START_MINUTE,
    s.END_MINUTE,
    s.SORT_ORDER,
    'Y'
);

MERGE INTO REGION_CODE t
USING (
    SELECT 'SEOUL' REGION_CODE, NULL PARENT_REGION_CODE, '서울특별시' REGION_NAME, 1 REGION_LEVEL FROM DUAL UNION ALL
    SELECT 'BUSAN', NULL, '부산광역시', 1 FROM DUAL UNION ALL
    SELECT 'DAEGU', NULL, '대구광역시', 1 FROM DUAL UNION ALL
    SELECT 'INCHEON', NULL, '인천광역시', 1 FROM DUAL UNION ALL
    SELECT 'GWANGJU', NULL, '광주광역시', 1 FROM DUAL UNION ALL
    SELECT 'DAEJEON', NULL, '대전광역시', 1 FROM DUAL UNION ALL
    SELECT 'ULSAN', NULL, '울산광역시', 1 FROM DUAL UNION ALL
    SELECT 'SEJONG', NULL, '세종특별자치시', 1 FROM DUAL UNION ALL
    SELECT 'GYEONGGI', NULL, '경기도', 1 FROM DUAL UNION ALL
    SELECT 'GANGWON', NULL, '강원특별자치도', 1 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK', NULL, '충청북도', 1 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM', NULL, '충청남도', 1 FROM DUAL UNION ALL
    SELECT 'JEONBUK', NULL, '전북특별자치도', 1 FROM DUAL UNION ALL
    SELECT 'JEONNAM', NULL, '전라남도', 1 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK', NULL, '경상북도', 1 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM', NULL, '경상남도', 1 FROM DUAL UNION ALL
    SELECT 'JEJU', NULL, '제주특별자치도', 1 FROM DUAL UNION ALL
    SELECT 'SEOUL_GANGNAM', 'SEOUL', '강남구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GANGDONG', 'SEOUL', '강동구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GANGBUK', 'SEOUL', '강북구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GANGSEO', 'SEOUL', '강서구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GWANAK', 'SEOUL', '관악구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GWANGJIN', 'SEOUL', '광진구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GURO', 'SEOUL', '구로구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_GEUMCHEON', 'SEOUL', '금천구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_NOWON', 'SEOUL', '노원구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_DOBONG', 'SEOUL', '도봉구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_DONGDAEMUN', 'SEOUL', '동대문구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_DONGJAK', 'SEOUL', '동작구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_MAPO', 'SEOUL', '마포구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_SEODAEMUN', 'SEOUL', '서대문구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_SEOCHO', 'SEOUL', '서초구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_SEONGDONG', 'SEOUL', '성동구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_SEONGBUK', 'SEOUL', '성북구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_SONGPA', 'SEOUL', '송파구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_YANGCHEON', 'SEOUL', '양천구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_YEONGDEUNGPO', 'SEOUL', '영등포구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_YONGSAN', 'SEOUL', '용산구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_EUNPYEONG', 'SEOUL', '은평구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_JONGNO', 'SEOUL', '종로구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_JUNG', 'SEOUL', '중구', 2 FROM DUAL UNION ALL
    SELECT 'SEOUL_JUNGNANG', 'SEOUL', '중랑구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_JUNG', 'BUSAN', '중구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_SEO', 'BUSAN', '서구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_DONG', 'BUSAN', '동구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_YEONGDO', 'BUSAN', '영도구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_BUSANJIN', 'BUSAN', '부산진구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_DONGNAE', 'BUSAN', '동래구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_NAM', 'BUSAN', '남구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_BUK', 'BUSAN', '북구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_HAEUNDAE', 'BUSAN', '해운대구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_SAHA', 'BUSAN', '사하구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_GEUMJEONG', 'BUSAN', '금정구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_GANGSEO', 'BUSAN', '강서구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_YEONJE', 'BUSAN', '연제구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_SUYEONG', 'BUSAN', '수영구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_SASANG', 'BUSAN', '사상구', 2 FROM DUAL UNION ALL
    SELECT 'BUSAN_GIJANG', 'BUSAN', '기장군', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_JUNG', 'DAEGU', '중구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_DONG', 'DAEGU', '동구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_SEO', 'DAEGU', '서구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_NAM', 'DAEGU', '남구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_BUK', 'DAEGU', '북구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_SUSEONG', 'DAEGU', '수성구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_DALSEO', 'DAEGU', '달서구', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_DALSEONG', 'DAEGU', '달성군', 2 FROM DUAL UNION ALL
    SELECT 'DAEGU_GUNWI', 'DAEGU', '군위군', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_JUNG', 'INCHEON', '중구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_DONG', 'INCHEON', '동구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_MICHUHOL', 'INCHEON', '미추홀구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_YEONSU', 'INCHEON', '연수구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_NAMDONG', 'INCHEON', '남동구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_BUPYEONG', 'INCHEON', '부평구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_GYEYANG', 'INCHEON', '계양구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_SEO', 'INCHEON', '서구', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_GANGHWA', 'INCHEON', '강화군', 2 FROM DUAL UNION ALL
    SELECT 'INCHEON_ONGJIN', 'INCHEON', '옹진군', 2 FROM DUAL UNION ALL
    SELECT 'GWANGJU_DONG', 'GWANGJU', '동구', 2 FROM DUAL UNION ALL
    SELECT 'GWANGJU_SEO', 'GWANGJU', '서구', 2 FROM DUAL UNION ALL
    SELECT 'GWANGJU_NAM', 'GWANGJU', '남구', 2 FROM DUAL UNION ALL
    SELECT 'GWANGJU_BUK', 'GWANGJU', '북구', 2 FROM DUAL UNION ALL
    SELECT 'GWANGJU_GWANGSAN', 'GWANGJU', '광산구', 2 FROM DUAL UNION ALL
    SELECT 'DAEJEON_DONG', 'DAEJEON', '동구', 2 FROM DUAL UNION ALL
    SELECT 'DAEJEON_JUNG', 'DAEJEON', '중구', 2 FROM DUAL UNION ALL
    SELECT 'DAEJEON_SEO', 'DAEJEON', '서구', 2 FROM DUAL UNION ALL
    SELECT 'DAEJEON_YUSEONG', 'DAEJEON', '유성구', 2 FROM DUAL UNION ALL
    SELECT 'DAEJEON_DAEDEOK', 'DAEJEON', '대덕구', 2 FROM DUAL UNION ALL
    SELECT 'ULSAN_JUNG', 'ULSAN', '중구', 2 FROM DUAL UNION ALL
    SELECT 'ULSAN_NAM', 'ULSAN', '남구', 2 FROM DUAL UNION ALL
    SELECT 'ULSAN_DONG', 'ULSAN', '동구', 2 FROM DUAL UNION ALL
    SELECT 'ULSAN_BUK', 'ULSAN', '북구', 2 FROM DUAL UNION ALL
    SELECT 'ULSAN_ULJU', 'ULSAN', '울주군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_SUWON', 'GYEONGGI', '수원시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_YONGIN', 'GYEONGGI', '용인시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GOYANG', 'GYEONGGI', '고양시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_HWASEONG', 'GYEONGGI', '화성시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_SEONGNAM', 'GYEONGGI', '성남시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_BUCHEON', 'GYEONGGI', '부천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_NAMYANGJU', 'GYEONGGI', '남양주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_ANSAN', 'GYEONGGI', '안산시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_PYEONGTAEK', 'GYEONGGI', '평택시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_ANYANG', 'GYEONGGI', '안양시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_SIHEUNG', 'GYEONGGI', '시흥시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_PAJU', 'GYEONGGI', '파주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GIMPO', 'GYEONGGI', '김포시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_UIJEONGBU', 'GYEONGGI', '의정부시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GWANGJU', 'GYEONGGI', '광주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_HANAM', 'GYEONGGI', '하남시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GWANGMYEONG', 'GYEONGGI', '광명시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GUNPO', 'GYEONGGI', '군포시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_YANGJU', 'GYEONGGI', '양주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_OSAN', 'GYEONGGI', '오산시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_ICHEON', 'GYEONGGI', '이천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_ANSEONG', 'GYEONGGI', '안성시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GURI', 'GYEONGGI', '구리시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_UIWANG', 'GYEONGGI', '의왕시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_POCHEON', 'GYEONGGI', '포천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_DONGDUCHEON', 'GYEONGGI', '동두천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GWACHEON', 'GYEONGGI', '과천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_YEOJU', 'GYEONGGI', '여주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_YANGPYEONG', 'GYEONGGI', '양평군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_GAPYEONG', 'GYEONGGI', '가평군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGGI_YEONCHEON', 'GYEONGGI', '연천군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_CHUNCHEON', 'GANGWON', '춘천시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_WONJU', 'GANGWON', '원주시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_GANGNEUNG', 'GANGWON', '강릉시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_DONGHAE', 'GANGWON', '동해시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_TAEBAEK', 'GANGWON', '태백시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_SOKCHO', 'GANGWON', '속초시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_SAMCHEOK', 'GANGWON', '삼척시', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_HONGCHEON', 'GANGWON', '홍천군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_HOENGSEONG', 'GANGWON', '횡성군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_YEONGWOL', 'GANGWON', '영월군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_PYEONGCHANG', 'GANGWON', '평창군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_JEONGSEON', 'GANGWON', '정선군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_CHEORWON', 'GANGWON', '철원군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_HWACHEON', 'GANGWON', '화천군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_YANGGU', 'GANGWON', '양구군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_INJE', 'GANGWON', '인제군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_GOSEONG', 'GANGWON', '고성군', 2 FROM DUAL UNION ALL
    SELECT 'GANGWON_YANGYANG', 'GANGWON', '양양군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_CHEONGJU', 'CHUNGBUK', '청주시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_CHUNGJU', 'CHUNGBUK', '충주시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_JECHEON', 'CHUNGBUK', '제천시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_BOEUN', 'CHUNGBUK', '보은군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_OKCHEON', 'CHUNGBUK', '옥천군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_YEONGDONG', 'CHUNGBUK', '영동군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_JEUNGPYEONG', 'CHUNGBUK', '증평군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_JINCHEON', 'CHUNGBUK', '진천군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_GOESAN', 'CHUNGBUK', '괴산군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_EUMSEONG', 'CHUNGBUK', '음성군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGBUK_DANYANG', 'CHUNGBUK', '단양군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_CHEONAN', 'CHUNGNAM', '천안시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_GONGJU', 'CHUNGNAM', '공주시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_BORYEONG', 'CHUNGNAM', '보령시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_ASAN', 'CHUNGNAM', '아산시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_SEOSAN', 'CHUNGNAM', '서산시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_NONSAN', 'CHUNGNAM', '논산시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_GYERYONG', 'CHUNGNAM', '계룡시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_DANGJIN', 'CHUNGNAM', '당진시', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_GEUMSAN', 'CHUNGNAM', '금산군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_BUYEO', 'CHUNGNAM', '부여군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_SEOCHEON', 'CHUNGNAM', '서천군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_CHEONGYANG', 'CHUNGNAM', '청양군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_HONGSEONG', 'CHUNGNAM', '홍성군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_YESAN', 'CHUNGNAM', '예산군', 2 FROM DUAL UNION ALL
    SELECT 'CHUNGNAM_TAEAN', 'CHUNGNAM', '태안군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_JEONJU', 'JEONBUK', '전주시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_GUNSAN', 'JEONBUK', '군산시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_IKSAN', 'JEONBUK', '익산시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_JEONGEUP', 'JEONBUK', '정읍시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_NAMWON', 'JEONBUK', '남원시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_GIMJE', 'JEONBUK', '김제시', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_WANJU', 'JEONBUK', '완주군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_JINAN', 'JEONBUK', '진안군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_MUJU', 'JEONBUK', '무주군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_JANGSU', 'JEONBUK', '장수군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_IMSIL', 'JEONBUK', '임실군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_SUNCHANG', 'JEONBUK', '순창군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_GOCHANG', 'JEONBUK', '고창군', 2 FROM DUAL UNION ALL
    SELECT 'JEONBUK_BUAN', 'JEONBUK', '부안군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_MOKPO', 'JEONNAM', '목포시', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_YEOSU', 'JEONNAM', '여수시', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_SUNCHEON', 'JEONNAM', '순천시', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_NAJU', 'JEONNAM', '나주시', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_GWANGYANG', 'JEONNAM', '광양시', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_DAMYANG', 'JEONNAM', '담양군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_GOKSEONG', 'JEONNAM', '곡성군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_GURYE', 'JEONNAM', '구례군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_GOHEUNG', 'JEONNAM', '고흥군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_BOSEONG', 'JEONNAM', '보성군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_HWASUN', 'JEONNAM', '화순군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_JANGHEUNG', 'JEONNAM', '장흥군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_GANGJIN', 'JEONNAM', '강진군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_HAENAM', 'JEONNAM', '해남군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_YEONGAM', 'JEONNAM', '영암군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_MUAN', 'JEONNAM', '무안군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_HAMPYEONG', 'JEONNAM', '함평군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_YEONGGWANG', 'JEONNAM', '영광군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_JANGSEONG', 'JEONNAM', '장성군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_WANDO', 'JEONNAM', '완도군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_JINDO', 'JEONNAM', '진도군', 2 FROM DUAL UNION ALL
    SELECT 'JEONNAM_SINAN', 'JEONNAM', '신안군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_POHANG', 'GYEONGBUK', '포항시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_GYEONGJU', 'GYEONGBUK', '경주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_GIMCHEON', 'GYEONGBUK', '김천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_ANDONG', 'GYEONGBUK', '안동시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_GUMI', 'GYEONGBUK', '구미시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_YEONGJU', 'GYEONGBUK', '영주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_YEONGCHEON', 'GYEONGBUK', '영천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_SANGJU', 'GYEONGBUK', '상주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_MUNGYEONG', 'GYEONGBUK', '문경시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_GYEONGSAN', 'GYEONGBUK', '경산시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_UISEONG', 'GYEONGBUK', '의성군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_CHEONGSONG', 'GYEONGBUK', '청송군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_YEONGYANG', 'GYEONGBUK', '영양군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_YEONGDEOK', 'GYEONGBUK', '영덕군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_CHEONGDO', 'GYEONGBUK', '청도군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_GORYEONG', 'GYEONGBUK', '고령군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_SEONGJU', 'GYEONGBUK', '성주군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_CHILGOK', 'GYEONGBUK', '칠곡군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_YECHEON', 'GYEONGBUK', '예천군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_BONGHWA', 'GYEONGBUK', '봉화군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_ULJIN', 'GYEONGBUK', '울진군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGBUK_ULLEUNG', 'GYEONGBUK', '울릉군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_CHANGWON', 'GYEONGNAM', '창원시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_JINJU', 'GYEONGNAM', '진주시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_TONGYEONG', 'GYEONGNAM', '통영시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_SACHEON', 'GYEONGNAM', '사천시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_GIMHAE', 'GYEONGNAM', '김해시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_MIRYANG', 'GYEONGNAM', '밀양시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_GEOJE', 'GYEONGNAM', '거제시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_YANGSAN', 'GYEONGNAM', '양산시', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_UIRYEONG', 'GYEONGNAM', '의령군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_HAMAN', 'GYEONGNAM', '함안군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_CHANGNYE', 'GYEONGNAM', '창녕군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_GOSEONG', 'GYEONGNAM', '고성군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_NAMHAE', 'GYEONGNAM', '남해군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_HADONG', 'GYEONGNAM', '하동군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_SANCHEONG', 'GYEONGNAM', '산청군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_HAMYANG', 'GYEONGNAM', '함양군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_GEOCHANG', 'GYEONGNAM', '거창군', 2 FROM DUAL UNION ALL
    SELECT 'GYEONGNAM_HAPCHEON', 'GYEONGNAM', '합천군', 2 FROM DUAL UNION ALL
    SELECT 'JEJU_JEJU', 'JEJU', '제주시', 2 FROM DUAL UNION ALL
    SELECT 'JEJU_SEOGWIPO', 'JEJU', '서귀포시', 2 FROM DUAL
) s
ON (t.REGION_CODE = s.REGION_CODE)
WHEN MATCHED THEN UPDATE SET
    t.PARENT_REGION_CODE = s.PARENT_REGION_CODE,
    t.REGION_NAME = s.REGION_NAME,
    t.REGION_LEVEL = s.REGION_LEVEL,
    t.ACTIVE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (
    REGION_CODE,
    PARENT_REGION_CODE,
    REGION_NAME,
    REGION_LEVEL,
    ACTIVE_YN
) VALUES (
    s.REGION_CODE,
    s.PARENT_REGION_CODE,
    s.REGION_NAME,
    s.REGION_LEVEL,
    'Y'
);

COMMIT;
